<table class="table table-bordered table-striped">
    <caption>table showing full detail of product</caption>
    <thead>
        <tr>
            <th>Key</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
        <tr>
            <td>id</td>
            <td><?php echo $data->_id ?></td>
        </tr>
        <tr>
            <td>name</td>
            <td><?php echo $data->name ?></td>
        </tr>
        <tr>
            <td>catageory</td>
            <td><?php echo $data->desc ?></td>
        </tr>
        <tr>
            <td>price</td>
            <td><?php echo $data->price ?></td>
        </tr>
        <tr>
            <td>stock</td>
            <td><?php echo $data->stock ?></td>
        </tr>
        <tr>
            <td>additional data</td>
            <td><?php foreach ($data['additionalData'] as $key => $value) {
                    echo $key . "=>" . $value;
                } ?>
            </td>
        </tr>
        <tr>
            <td>variations</td>
            <td><?php foreach ($data['variations'] as $key => $value) {
                    echo $key . "=>" . $value . "<br>";
                } ?>
            </td>

        </tr>
    </tbody>
</table>
<a href='index' class='btn btn-primary'>Back</a>
