<!-- Add Products Page -->
<?php  require_once APP_PATH.'/admin/assets/header.php';;?>
<div style="margin-left:370px ;width:400px; background-color:aliceblue;border-radius:10px;margin-top:5px "
class="text-center p-2">
    <h2>Add Products</h2>
    <?php echo $this->tag->form("../admin/product/add"); ?>
    <br>
    <p>
        <label for="name" class="col-4">Name</label>
        <?php echo $this->tag->textField(["name", 'class' => 'form-control']); ?>
    </p>
    <p>
        <label for="description">Catageory</label>
        <?php echo $this->tag->textField(["desc", 'class' => 'form-control']); ?>
    </p>
    <p>
        <label for="price">Price</label>
        <?php echo $this->tag->numericField(["price", 'class' => 'form-control']); ?>
    </p>
    <p>
        <label for="stock">Stock</label>
        <?php echo $this->tag->numericField(["stock", 'class' => 'form-control']); ?>
    </p>
    <label for="stock">Additional Data</label>
    <div class='additional'>
        <p class='d-flex' >
            <input type="text" name='additionaldata[]' placeholder='additional key' class='form-control m-1'>
            <input type="text" name='additionaldatavalue[]' placeholder='additional Value' class="form-control m-1">
            <input type="button" value="+" id='add' onclick=addAdditional() class='btn btn-primary m-1'>
            <input type="button" value="-" id='sub' onclick=subAdditional(this) class='btn btn-primary m-1'>
        </p>
    </div>
    <label for="stock">Variations</label>
    <div class='data'>
        <p class='d-flex ' id='metaData'>
            <select name="metaKey[]" class="form-control text-center m-1">
                <option disabled>Choose any One</option>
                <option>color</option>
                <option>size</option>
                <option>fabric</option>
            </select>

            <input type="text" name='metaValue[]' class='form-control m-1' placeholder="value">
            <input type="text" name='metaValuePrice[]' class='form-control m-1' placeholder='amount'>
            <input type="button" value="+" id='add' onclick=addMeta() class='btn btn-primary m-1'>
            <input type="button" value="-" id='sub' onclick=subMeta(this) class='btn btn-primary m-1'>
        </p>
    </div>
    <p>
        <?php echo $this->tag->submitButton(["Add", 'class' => 'btn btn-primary', 'name' => 'submit']); ?>
    </p>

    </form>
</div>
