<?php include_once APP_PATH . '/assets/header.php'; ?>
<!-- Add Order Page -->
<div style="margin-left:370px ;width:400px; background-color:aliceblue;border-radius:10px;margin-top:5px"
class="text-center p-2">
    <h2>Add Orders</h2>
    <br>
    <p>
        <label for="c_name">Customer Name</label>
        <?php echo $this->tag->textField(["name", 'class' => 'form-control', 'id'=>'name']); ?>
    </p>
    <p>
        <label for="c_address">Customer Address</label>
        <?php echo $this->tag->textField(["address", 'class' => 'form-control' ,'id'=>'address']); ?>
    </p>
    <p>
        <label for="zipcode">ZipCode</label>
        <?php echo $this->tag->numericField(["zipcode", 'class' => 'form-control' , 'id'=>'zip']); ?>
    </p>
    <p>
    <form action="#" method='post'>
        <label for="product">Product</label>
        <select name="product" id="product" class="form-control text-center" onchange="this.form.submit();">
            <?php
            echo "<option>$_POST[product]</option>";
            foreach ($data as $value) {
                echo "<option>$value->name</option>";
            }
            ?>
        </select>
    </form>
    <?php
    if (isset($_POST['product'])) {
        echo "<br><label for='product'>Variaions</label><br>";
        $product = $_POST['product'];
        $collection = $this->mongo->products;
        $data = $collection->findOne(['name' => $product]);
        echo "<select  class='form-control text-center' id='variations' name='variations'>";
        foreach ($data['variations'] as $key => $value) {
            echo "<option>$value</option>";
        }
        echo "</select>";
    }
    ?>
    </p>
    <p>
        <label for="stock">Quantity</label>
        <?php echo $this->tag->numericField(["qty", 'class' => 'form-control' ,'id'=>'qty']); ?>
    </p>

    <p>
        <button onclick=addOrder() class="btn btn-primary">Add Order</button>
    </p>

    </form>
</div>

